@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYWIxOWVmNmFjNzdhM2RiNGIyOTFiMiIsImVtYWlsIjoiYmFkYXJzaDIwMDFAZ21haWwuY29tIiwicm9sZSI6MCwiaWF0IjoxNjM4NjMzMjM2LCJleHAiOjE2Mzg2MzY4MzZ9.A1Rmeuf4WCEEEk8lke1YYuciZi-nAKKVQnaU7hPj938

# # User Signup
# POST http://127.0.0.1:3333/api/signup HTTP/1.1
# Content-Type: application/json

# {
#     "firstname": "Adarsh",
#     "lastname": "Badagala",
#     "email": "badarsh2001@gmail.com",
#     "contact_number": "7382468891",
#     "password": "87654321",
#     "password2": "87654321"
# }


# User login
POST http://127.0.0.1:3333/api/login HTTP/1.1
Content-Type: application/json

{
    "email": "badarsh2001@gmail.com",
    "password": "87654321"
}