@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYWM1MzczN2VlNmEzMmYyMDM3NTZmYyIsImVtYWlsIjoiYmFkYXJzaDIwMDFAZ21haWwuY29tIiwicm9sZSI6MCwia2FybWFfcG9pbnRzIjoxNzUsImZpcnN0bmFtZSI6IkFkYXJzaCIsImxhc3RuYW1lIjoiQmFkYWdhbGEiLCJpYXQiOjE2Mzg2OTIzOTEsImV4cCI6MTYzODY5NTk5MX0.cKdmmEV5bWO0Tpf-LVOJT79HuqjG6VDxNNqVanimAOU



# # Creating a request
# POST http://127.0.0.1:3333/api/request HTTP/1.1
# Content-Type: application/json
# Authorization: {{token}}

# {
#     "location": "Eluru",
#     "request_name": "inverter",
#     "request_description": "Amaron",
#     "karma_points": 99
# }


# # Accepting a request
# GET http://127.0.0.1:3333/api/request/61ab51d2f36b30423ce40e38 HTTP/1.1
# Authorization: {{token}}