@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYWM0YWFlZDFiY2IyNGNlMGYwYzZmYyIsImVtYWlsIjoiZGFtYXJlc2h3YXJha3VtYXJAZ21haWwuY29tIiwicm9sZSI6MCwia2FybWFfcG9pbnRzIjoxMjUsImZpcnN0bmFtZSI6IkRoYW1hcmVzaHdhcmFrdW1hciIsImxhc3RuYW1lIjoiR2FuZGlrb3RhIiwiaWF0IjoxNjM4NzAzNzAwLCJleHAiOjE2Mzg3MDczMDB9.75P7GHziI20CpItGLFlZDkou7pjCjW7KomARZJLOs9Y



# Creating a request
POST http://127.0.0.1:3333/api/request HTTP/1.1
Content-Type: application/json
Authorization: {{token}}

{
    "location": "Eluru",
    "request_name": "inverter",
    "request_description": "Amaron",
    "karma_points": 99
}


# # Accepting a request
# GET http://127.0.0.1:3333/api/request/61ab51d2f36b30423ce40e38 HTTP/1.1
# Authorization: {{token}}